import {
  Box,
  Building2,
  Calculator,
  Clock,
  Cloud,
  Cog,
  Coins,
  DraftingCompass,
  FileText,
  GitMerge,
  Layers,
  PencilRuler,
  ScanLine,
  Search,
  Wrench,
} from "lucide-react";

export const serviceShowcase = [
  {
    icon: Building2,
    title: "Architectural, Structural & MEP BIM Modeling",
    desc: "Discipline-rich 3D BIM models developed for design clarity, coordination, and construction-ready delivery.",
    graphic: "/service-graphics/bim-modeling.jpg",
    focus: "50% 48%",
  },
  {
    icon: GitMerge,
    title: "BIM Coordination",
    desc: "Integrated model coordination across architecture, structure, and MEP to reduce rework before site execution.",
    graphic: "/service-graphics/bim-coordination.jpg",
    focus: "54% 48%",
  },
  {
    icon: Search,
    title: "Clash Detection",
    desc: "Early identification and resolution of spatial conflicts for smoother construction sequencing and installation.",
    graphic: "/service-graphics/clash-detection.jpg",
    focus: "54% 50%",
  },
  {
    icon: ScanLine,
    title: "Scan to BIM / Point Cloud Modeling",
    desc: "Reality-capture data converted into accurate, intelligent BIM models for renovation and as-built workflows.",
    graphic: "/service-graphics/scan-to-bim.jpg",
    focus: "50% 48%",
  },
  {
    icon: Box,
    title: "Revit Family Creation",
    desc: "Smart parametric families and reusable BIM content built for consistency, accuracy, and project standards.",
    graphic: "/service-graphics/revit-family.jpg",
    focus: "50% 50%",
  },
  {
    icon: Clock,
    title: "4D BIM Scheduling",
    desc: "Time-linked BIM sequencing to visualize project progress, construction phases, logistics, and site planning.",
    graphic: "/service-graphics/four-d-bim.jpg",
    focus: "54% 50%",
  },
  {
    icon: Calculator,
    title: "Quantity Takeoff",
    desc: "Model-driven quantities and BOQ support for confident planning, procurement, and tendering decisions.",
    graphic: "/service-graphics/material-takeoff.jpg",
    focus: "54% 50%",
  },
  {
    icon: Coins,
    title: "5D BIM & Cost Estimation",
    desc: "Cost-aware BIM workflows that connect model intelligence with budgets, estimates, and project controls.",
    graphic: "/service-graphics/cost-estimation.jpg",
    focus: "54% 50%",
  },
  {
    icon: DraftingCompass,
    title: "Construction Documentation & Shop Drawings",
    desc: "Coordinated drawing sets, details, and documentation packages prepared for approvals and construction use.",
    graphic: "/service-graphics/bim-modeling.jpg",
    focus: "50% 57%",
  },
  {
    icon: Cog,
    title: "Digital Engineering & BIM Management",
    desc: "Standards-led BIM workflows, model audits, documentation support, and digital project delivery management.",
    graphic: "/service-graphics/bim-coordination.jpg",
    focus: "50% 58%",
  },
];

export const homepageServices = [
  {
    icon: Box,
    title: "Building Information Modeling",
    desc: "Intelligent 3D models across all disciplines.",
    graphic: "/service-graphics/bim-modeling.jpg",
    focus: "50% 48%",
  },
  {
    icon: PencilRuler,
    title: "CAD Drafting",
    desc: "Precise, standards-compliant drawing production.",
    graphic: "/service-graphics/bim-modeling.jpg",
    focus: "50% 68%",
  },
  {
    icon: ScanLine,
    title: "Scan to BIM",
    desc: "Reality capture converted into accurate BIM.",
    graphic: "/service-graphics/scan-to-bim.jpg",
    focus: "50% 48%",
  },
  {
    icon: Wrench,
    title: "MEP BIM",
    desc: "Coordinated mechanical, electrical, plumbing models.",
    graphic: "/service-graphics/bim-coordination.jpg",
    focus: "54% 48%",
  },
  {
    icon: Building2,
    title: "Structural BIM",
    desc: "Detailed structural modeling and documentation.",
    graphic: "/service-graphics/bim-modeling.jpg",
    focus: "50% 72%",
  },
  {
    icon: FileText,
    title: "Construction Documentation",
    desc: "Construction-ready drawing sets.",
    graphic: "/service-graphics/bim-modeling.jpg",
    focus: "50% 35%",
  },
  {
    icon: GitMerge,
    title: "BIM Coordination",
    desc: "Multi-discipline coordination workflows.",
    graphic: "/service-graphics/bim-coordination.jpg",
    focus: "54% 48%",
  },
  {
    icon: Search,
    title: "Clash Detection",
    desc: "Proactive interference resolution.",
    graphic: "/service-graphics/clash-detection.jpg",
    focus: "54% 50%",
  },
  {
    icon: Cloud,
    title: "Point Cloud Modeling",
    desc: "Point cloud to intelligent BIM elements.",
    graphic: "/service-graphics/scan-to-bim.jpg",
    focus: "44% 48%",
  },
  {
    icon: Layers,
    title: "Digital Twin",
    desc: "Live digital replicas of built assets.",
    graphic: "/service-graphics/scan-to-bim.jpg",
    focus: "62% 45%",
  },
  {
    icon: Cog,
    title: "CAD Automation",
    desc: "Dynamo and scripted productivity workflows.",
    graphic: "/service-graphics/revit-family.jpg",
    focus: "50% 50%",
  },
  {
    icon: Calculator,
    title: "Quantity Takeoff",
    desc: "Model-driven BOQ and estimation.",
    graphic: "/service-graphics/material-takeoff.jpg",
    focus: "54% 50%",
  },
];
